### ISSUE TITLE
forced to map props when using redux

### ISSUE THREAD

**Issue by caranicas** [react-component/time-picker#12]
When I wrap time picker using connect binding in the redux react library i am no longer able to set default props on the object within the wrapper .

Normally if I wanted to create a time that hid all the seconds
```
let MyTimePicker = () => (
  <TimePicker
   showSecond={false}
  />
);
MyTimePicker = connect(mapStateToProps,mapDispatchToProps)(TimePicker);
```

And then in the map function I would control the disabled hours like this

```
const mapStateToProps = (
  state,
  ownProps
) => {
  return {
   disabledHours:() => {
      ownProps.determineDisabledHours(state)
  };
}
```

But this isn't the case, now all props i want to pass need to be passed in through the map. 

```
const mapStateToProps = (
  state,
  ownProps
) => {
  return {
   showSecond:false,
  hideDisabledOptions:true,
}
```

This isn't the largest inconvenience in the world, but it is puzzling because I've never had an issue like this before. 

Would you happen to know if the time picker is written in an immutable way?

**Comment by yiminghe** [comment]
can you provide a working demo? (make a gh-pages from your demo repo)
