### ISSUE TITLE
Any way to put '00' instead of '12' when using use12Hours format and is selected 'am'?

### ISSUE THREAD

**Issue by CarlosOrozc** [react-component/time-picker#175]
Any way to put **00** instead of **12** when using use12Hours format and is selected **am**?

<img width="721" alt="Screen Shot 2019-11-29 at 9 58 03 AM" src="https://user-images.githubusercontent.com/8071575/69881047-58f17b00-1291-11ea-9bc7-81d5a4605b86.png">

**Comment by dons20** [comment]
You do realize that the whole point of the 12 hour syntax is using the hours of 01-12? In other words, there is no 00 hour in the 12 hour system. You'd have to be using 24 hours instead.
