### ISSUE TITLE
TimePicker popup doesn't open

### ISSUE THREAD

**Issue by Sunil6591** [react-component/time-picker#18]
Not sure what is wrong.
Here are lines i have it in my component

```
import 'rc-time-picker/assets/index.css';
import TimePicker from 'rc-time-picker';
```

And in the `render()`

```
<TimePicker style={{ width: 100 }}
          defaultValue={moment()}
          showSecond={false} />
```

And here is what i see
![image](https://cloud.githubusercontent.com/assets/4942980/17846332/88ff82ee-6865-11e6-9340-72c4b8b39909.png)

When i click on it, it doesn't open. I tried to debug, and the props `onOpen` is pointing to `noop()` empty function. Not sure if i have to provide the `onOpen()` function

I sure there is something stupid on my side, but being struggling for long time, help pls!

**Comment by smaccoun** [comment]
I noticed that for me the issue seems to be in trying to import the css file. When I just included it in my index.html it seemed to work fine

**Comment by afc163** [comment]
Try newest version fo `rc-time-picker`.
