### ISSUE TITLE
Styling panels and select when not using seconds

### ISSUE THREAD

**Issue by camway** [react-component/time-picker#19]
I was going to try to fork and make a pull request, but changed my mind after the styles were located in .less files (I'll have to do some reading into what those are, it looks interesting).

I tried using the time select and after disabling the seconds display, wasn't really happy with the blank white column on the far right side of the dropdown.  Here is my css fix if you think it belongs in the project feel free it implement. I'm currently just overwriting this part of the css file.  It should work regardless of whether you are using the seconds or not.

```
.rc-time-picker-panel-combobox{
  display: table;
  width: 100%;
}

.rc-time-picker-panel-select{
  /* float: left; */
  /* width: 56px; */
  display: table-cell;
}
```

I think this made a few other styles useless so it may require cleanup. In its current state, it handles the width differences for both hours/minutes/seconds and hours/minutes.

**Comment by alexanderwe** [comment]
I know that this is a little bit old, but as this issue still applies today here is another way to solve it using Flexbox

```
.rc-time-picker-panel-combobox{
  display: flex;
}

.rc-time-picker-panel-select{
  flex: 1;
}
```
