### ISSUE TITLE
IE8 下报错

### ISSUE THREAD

**Issue by afc163** [react-component/time-picker#2]
这个页面 http://react-component.github.io/time-picker/examples/pick-time.html 在 IE8 下报错。

```
SCRIPT5028: Function.prototype.apply: 缺少 Array 或 arguments 对象 
```

定位到此行：https://github.com/react-component/time-picker/blob/8133e8cf3b37b2be764616493ade7c7a7678fce1/src/TimePicker.jsx#L13

**Comment by iceman1212** [comment]
不用 Array.apply 
换成Array.push() 
https://github.com/react-component/time-picker/pull/4/files

**Comment by wuzhao** [comment]
https://github.com/react-component/time-picker/pull/4
