### ISSUE TITLE
support for maximum, minimum or time ranges?

### ISSUE THREAD

**Issue by cshanejennings** [react-component/time-picker#20]
Do you have any plans to support a maximum or minimum time or maybe a range of available times to select from?

**Comment by andyrichardson** [comment]
I'd like to have some feature similar to this. I'm looking to only show 15 minute intervals (00, 15, 30, 45) but from what I can tell, this isn't possible.

Thanks for the plugin!

**Comment by sveinpg** [comment]
@afc163 Any plans adding this soon? Otherwise I'll create a PR.

**Comment by afc163** [comment]
Use `disabledXxxxx` and `hideDisabledOptions` like antd does: https://ant.design/components/time-picker/#components-time-picker-demo-disable-options
