### ISSUE TITLE
OnBlur callback 

### ISSUE THREAD

**Issue by equilerex** [react-component/time-picker#23]
Hi there, 

Been implementing the plugin but ran into an issue... i can "open" the timepicker by passing state to the open parameter using open={this.state.openTimepicker} (got a component block with an icon, extra padding etc that should trigger it)

however, when i close the timepicker, the "openTimepicker" state remains true  so when ever a state change happens anywhere else in the app, the open property is enforced again and the timepicker will pop up again... there for i would need access to onBlur callback where i can set the openTimepicker to false again... i think it would be fairly useful in many different scenarious to implement this functionality

**Comment by Jiiun** [comment]
![image](https://cloud.githubusercontent.com/assets/13991287/20834198/f89f4fd0-b8ce-11e6-815d-89c26a98bbd9.png)
this is how i add the blur callback, I create a component that wrap timepicker

**Comment by monapasan** [comment]
@equilerex if it's still relevant:
There is a [onOpen](https://github.com/react-component/time-picker/blob/master/src/TimePicker.jsx#L41) and  [onClose](https://github.com/react-component/time-picker/blob/master/src/TimePicker.jsx#L42) property.
You can use that.
Unfortunately, this is not documented.
