### ISSUE TITLE
Support AM/PM

### ISSUE THREAD

**Issue by andresmijares** [react-component/time-picker#27]
I see there is a closed issue on this but it does not solve the doubt,

Any idea if we can make it work with AM/PM system?

Regards!

**Comment by eugenehp** [comment]
yeah, it would be great to have an option to specify am/pm formatting inside selector as well.
https://github.com/react-component/time-picker/blob/e59f4eae17cbfd7eed19cd385ec64312ffe266c4/src/Panel.jsx#L10-L18

**Comment by alanqthomas** [comment]
+1
Hard to believe this library hasn't considered AM/PM at all.

**Comment by afc163** [comment]
@shaleynikov is working on it.

https://github.com/react-component/time-picker/pull/34

**Comment by megawac** [comment]
Time to close this?
