### ISSUE TITLE
change the size of input, font-size 

### ISSUE THREAD

**Issue by kgrubic** [react-component/time-picker#32]
I have tried to increase the size of input, but without luck. Can we make component a little bit more modular.

**Comment by MathieuDebit** [comment]
It's as easy as override CSS rules. Here is an example with Webpack and SCSS:

```
// styles.scss

@import '~rc-time-picker/assets/index.css';

.rc-time-picker-input {
  height: 50px;
}
```

**Comment by kgrubic** [comment]
Thanks, I know :) . But I was hoping that I can pass some props to TimePicker and that will have an impact on rc-time-picker-input class.

**Comment by MathieuDebit** [comment]
Yes I see, but this is the recommended way for Airbnb's `react-dates`, so I guess it's a good one 👌

https://github.com/airbnb/react-dates#theming

**Comment by abrad45** [comment]
I think props / custom classes are a better way to handle this. It works great if you use less / scss / stylus / whatever the project uses, but if not, you're SOL
