### ISSUE TITLE
Moment.js

### ISSUE THREAD

**Issue by mperazac** [react-component/time-picker#46]
Hi, Can the value and defaultValue props can be set up without using moment.js but pure javascript?

**Comment by paranoidjk** [comment]
@mperazac We are disucuss this problem right now, you can share your opnion at https://github.com/ant-design/ant-design-mobile/issues/1217

**Comment by viperfx** [comment]
@paranoidjk Is this merged in? It looks like the issue you linked has commits leading to moment being removed but this does not reflect with what the current docs say

**Comment by paranoidjk** [comment]
@viperfx It's been released in antd-mobile@2, see https://github.com/ant-design/ant-design-mobile/releases/tag/2.0.0.

![2018-06-14 10 13 49](https://user-images.githubusercontent.com/7971415/41387862-d0fc26ce-6fbb-11e8-9c45-0e56bc87f8e1.jpg)

**Comment by viperfx** [comment]
Okay great! What about this repo?

**Comment by behagoras** [comment]
Please, please, please take time to review this issue
