### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by warmhug** [react-component/time-picker#5]
建议去掉 `hourOptions ` `minuteOptions ` `secondOptions `，感觉实际业务需求应该不是这样子。改为`限制只能选择某个时间段里的时间`，如图：
<img width="343" alt="be4bba1b1d94e070c4135817a2cf79a4" src="https://cloud.githubusercontent.com/assets/2011119/11583454/f9151e94-9a94-11e5-80d9-304f9867eb97.png">

注意：`min-time` `max-time`都设置或只设置其中一项，以及与 datepicker 共用一个时间时可能的问题。

**Comment by yiminghe** [comment]
#6
