### ISSUE TITLE
实现 disabledTime 功能

### ISSUE THREAD

**Issue by yiminghe** [react-component/time-picker#6]
min: 22:29 
max: 23:59

![xx](http://gtms03.alicdn.com/tps/i3/TB1iHXOKVXXXXX6XXXXOIAPOXXX-686-786.png)

```js
<TimePicker {...options} />


cons options = {
allowHour(){
  return [22,23];
}  ,
allowMinutes(h){
  return h===22?[]:[] 
},
allowSeconds(h, m) {
  return 
},
}

```

**Comment by afc163** [comment]
hourOptions minuteOptions secondOptions 主要是为了实现只选 `0` `30` 这样的功能。

和 disabled 其实不是一回事。

**Comment by janlay** [comment]
接口设计中，对是否包含边界很难直观看到，建议用数学区间的表示方式，并支持仅定义上限或下限，如 `[10, 20)`, `(, 100)`, `[0,]`，即省略的时候，中括号和圆括号均可接受。

API 名字可以用 validRange, 支持上面说的字符串；同时增加一个 validationHandler 对每一项的渲染进行判断以支持复杂的自定义规则。

**Comment by afc163** [comment]
讨论后使用以下 API：

```js
cons options = {
  disabledHours(h, m, s) {
    return [0 ... 21];
  },
  disabledMinutes(h, m, s) {
    return h === 22 ? [ 0...31 ] : [ ];
  },
  disabledSeconds(h, m, s) {
    return [];
  },
};

<TimePicker {...options} />
```

另外，增加 `hideDisabled` 属性，配合以上属性可以实现原来 hourOptions minuteOptions secondOptions 的功能，**hourOptions minuteOptions secondOptions 相应去掉**。

**Comment by yiminghe** [comment]
加个需求： 动态设置 disabled 后，如果当前 value 符合 disabled，自动调整到一个 可以 enable 的 value，并触发 onChange
