### ISSUE TITLE
TimePicker not scrolling on Modal 

### ISSUE THREAD

**Issue by James2516** [react-component/time-picker#64]
https://codesandbox.io/s/6lol2kz3v3

When the modal is scrolled, the timepicker just stays on the same position instead of getting scrolled together with the other components.

**Comment by keawade** [comment]
@James2516, did you fix this? If so, could you post your solution, please?

**Comment by James2516** [comment]
Add this prop to the component: `getPopupContainer={triggerNode => triggerNode.parentNode}`.

**Comment by bot19** [comment]
Still works in 4/2020, even though `getPopupContainer` isn't listed in the docs. Thanks @James2516

**Comment by geoeg** [comment]
[Bug] getPopupContainer missing in the TimePickerProps, so it triggers an error when using rc-time-picker TypeScript.
