### ISSUE TITLE
Hide disabled hours/minutes/...

### ISSUE THREAD

**Issue by jonathanasquier** [react-component/time-picker#74]
Hi, I want to enable only 1/4 of hours (10:00, 10:15, 10:30, 10:45) but right now I have a list of 56 disabled minutes and 4 enabled, which is far from the best user experience
Would it be possible to hide the disabled hours/minutes/... ?

thanks!

**Comment by afc163** [comment]
https://github.com/react-component/time-picker/pull/72 may resolve your problem.

**Comment by jonathanasquier** [comment]
Thanks I'll check
