### ISSUE TITLE
浮层中的某一栏会消失

### ISSUE THREAD

**Issue by benjycui** [react-component/time-picker#9]
打开 [demo](http://react-component.github.io/time-picker/examples/pick-time.html)，点开 TimePicker，在下面选择时间那几栏随便移动几下鼠标就可以看到这情况了。

![image](https://cloud.githubusercontent.com/assets/3580607/11734613/f189afdc-9ff3-11e5-8e7f-994749be767f.png)

今天刚升级的 Chorme，Version 47.0.2526.80 (64-bit)。

**Comment by afc163** [comment]
浏览器渲染问题，加了个 `position: relative` 就好了。

**Comment by afc163** [comment]
加了之后有其他问题。
