### ISSUE TITLE
On touch devices the virtual keyboard popup is undesirable.

### ISSUE THREAD

**Issue by JesperWe** [react-component/time-picker#91]
Since the TimePicker has an input field, a touch device will pop up the virtual keyboard when the picker is shown. On smaller screens (phones) this is very undesirable since it leaves very little screen space for the TimePicker widget itself and causes ugly scrolling.

The PR #80 gives the ability to solve this, since the virtual keyboard is *not* shown for input fields with a `readonly` attribute.

**Comment by yesmeck** [comment]
Closing since #80 has been merged.
