### ISSUE TITLE
Get event target onChange()

### ISSUE THREAD

**Issue by jacoahmad** [react-component/time-picker#92]
Hi, thanks for the awesome lib, but I have a question regarding how to get the event target onChange? 

`onChange(e) { console.log(e, moment(e, "HH:mm")) } // Currently, the event only pass the value, I want to get the target name etc`

I wish you could help me, and correct me if I'm wrong.

**Comment by yesmeck** [comment]
Why do you want get event?

**Comment by yesmeck** [comment]
Close since no response.

**Comment by lardissone** [comment]
A reason to expect the real event on change is to use with other libraries that expects the entire event on the onChange.

For example [Formik](https://github.com/jaredpalmer/formik)

**Comment by comradebeck** [comment]
Any update on this?
